### ISSUE TITLE
Mixed examples

### ISSUE THREAD

**Issue by svendeckers** [feathersjs-ecosystem/feathers-authentication-custom#2]
Hi,

I'm trying to set up a custom authentication on my Feathers app, and I have a few question about these examples here.

1. In the snippets, `app.configure(authentication(settings));` is used. Is this authentication coming from `feathers generate authentication`? I tried this with a simple `Username + Password (Local)`, is that ok...? I'm assuming whichever authentication I choose, I can overwrite it with my `CustomVerfier` class?

2. So when looking at the examples here, the snippets always use `app.configure(authentication(settings));` and after that the custom authentication is configured. But then in the complete example it's a little different, `.configure(auth({ secret: 'super secret' }))` is being used. Does it matter? I'm asking because I'm getting the following error when I start the app:

```
Error: Can not find app.passport. Did you initialize feathers-authentication before feathers-authentication-custom?
    at Function.customAuth (/my-backend/node_modules/feathers-authentication-custom/lib/index.js:22:13)
    at Function.configure (/my-backend/node_modules/@feathersjs/feathers/lib/application.js:59:8)
    at Object.<anonymous> (/my-backend/src/app.js:50:5)
```

This is my code:
```
// ...
const authentication = require('./authentication');
const custom = require('feathers-authentication-custom');
// ...
app.configure(middleware);

app.configure(authentication);
app.configure(custom({ Verifier: CustomVerifier }));

app.configure(services);
// ...
```

and `authentication.js` is just the standard:
```
const { AuthenticationService, JWTStrategy } = require('@feathersjs/authentication');
const { LocalStrategy } = require('@feathersjs/authentication-local');
const { expressOauth } = require('@feathersjs/authentication-oauth');

module.exports = app => {
  const authentication = new AuthenticationService(app);

  authentication.register('jwt', new JWTStrategy());
  authentication.register('local', new LocalStrategy());

  app.use('/authentication', authentication);
  app.configure(expressOauth());
};
```

Any help is appreciated!

**Comment by daffl** [comment]
This module is not compatible with Feathers v4. In Feathers 4, custom authentication can be implemented by creating [your own authentication strategy](https://docs.feathersjs.com/api/authentication/strategy.html).

I was meaning to archive this repository so this was a good reminder. If you have any questions about the v4 strategies, please feel free to create an issue in the [Feathers repository](https://github.com/feathersjs/feathers).
